### ISSUE TITLE
Credit @sindresorhus 

### ISSUE THREAD

**Issue by jamiebuilds** [ameerthehacker/cli-spinners#1]
Since this project copies a lot of content from @sindresorhus's [cli-spinners](https://github.com/sindresorhus/cli-spinners) and [ora](https://github.com/sindresorhus/ora) packages it would be good to give him and those projects credit for a good chunk of the work here.

**Comment by ameerthehacker** [comment]
@jamiebuilds it is true I will add credits in the README.md soon

**Comment by ameerthehacker** [comment]
@jamiebuilds I have added credits for the @sindresorhus package in the README, please feel free to create a PR if you want to add more!
